name: PythonFlaskRun Check

on: [push]

jobs:
  check_flask:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install autocomplete==0.0.104 \
                      blinker==1.8.2 \
                      bottle==0.13.1 \
                      click==8.1.7 \
                      filelock==3.16.1 \
                      Flask==3.0.3 \
                      fsspec==2024.9.0 \
                      importlib_metadata==8.5.0 \
                      imutils==0.5.4 \
                      itsdangerous==2.2.0 \
                      Jinja2==3.1.4 \
                      MarkupSafe==2.1.5 \
                      mpmath==1.3.0 \
                      networkx==2.8.8 \
                      numpy==2.0.2 \
                      opencv-python==4.10.0.84 \
                      pillow==11.0.0 \
                      sympy==1.13.1 \
                      torch==2.5.0+cpu \
                      torchvision==0.20.0+cpu \
                      typing_extensions==4.12.2 \
                      Werkzeug==3.0.4 \
                      zipp==3.20.2 -f https://download.pytorch.org/whl/torch_stable.html

      - name: Start Flask app
        env:
          FLASK_APP: app.py  # Update with your Flask app's entry file if different
        run: |
          nohup flask run &  # Run Flask in the background
          sleep 5  # Wait for the server to start

      - name: Check if Flask app is running
        run: |
          if curl --fail http://127.0.0.1:5000/; then
            echo "Flask app is running."
          else
            echo "Flask app is not running."
            exit 1
          fi

      - name: Stop Flask app
        run: |
          pkill -f "flask run"  # Stops the Flask app process
